services:
  - type: web
    name: brazenbox
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SUPABASE_URL
        value: https://vmshwnvwtobwdvcuahvk.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
